# Generated by Django 4.2.4 on 2023-10-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital_name',
            name='Image',
            field=models.ImageField(upload_to='hospital/Images'),
        ),
    ]
